from __future__ import annotations
from pathlib import Path
from typing import Iterable

def format_ppl(text: str) -> str:
    out=[]
    for raw in text.splitlines():
        line=raw.rstrip()
        out.append(line)
    return "\n".join(out).rstrip()+"\n"

def init_project(target: str | Path, force: bool=False) -> Path:
    root=Path(target)
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Directory is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)
    (root/"examples").mkdir(exist_ok=True)
    (root/"tests").mkdir(exist_ok=True)
    (root/"app.ppl").write_text('APP MyPPLApp\n\nINPUT request\n    text: TEXT\n\nAGENT Classifier\n\n    INPUT request\n\n    CLASSIFY request.text AS\n        GREETING\n        QUESTION\n        OTHER\n\n    OUTPUT\n        category\n        confidence\n\nWORKFLOW Main\n\n    RECEIVE request\n    RUN Classifier\n    RETURN Classifier.category\n', encoding='utf-8')
    (root/"README.md").write_text('# PPL App\n\nGenerated by `ppl init`. Start with `app.ppl`.\n', encoding='utf-8')
    return root

def diagnostics_from_exception(exc: Exception) -> str:
    return f"ERROR: {exc.__class__.__name__}: {exc}"

def repl_lines(lines: Iterable[str]) -> list[str]:
    results=[]
    for line in lines:
        s=line.strip()
        if not s: continue
        if s in {':help',':quit',':exit'}: results.append(s)
        else: results.append(f'accepted: {s}')
    return results
