from __future__ import annotations
from pathlib import Path
from typing import Iterable

SCRIPT_PPL = """APP MyScript

WORKFLOW Main
    LET message = "Hello, world"
    PRINT message
    RETURN message
"""

APP_PPL = """APP MyPPLApp

INPUT request
    text: TEXT

AGENT Classifier

    INPUT request

    CLASSIFY request.text AS
        GREETING
        QUESTION
        OTHER

    OUTPUT
        category
        confidence

WORKFLOW Main

    RECEIVE request
    RUN Classifier
    RETURN Classifier.category
"""

PROVIDERS_EXAMPLE = """{
  "provider": "local",
  "model": null,
  "profiles": {
    "dev": { "provider": "local" },
    "prod": { "provider": "openai", "model": "gpt-4.1-mini" }
  },
  "active_profile": "dev"
}
"""

TOOLS_EXAMPLE = """{
  "custom_action": "mymodule:my_handler"
}
"""


def format_ppl(text: str) -> str:
    out=[]
    for raw in text.splitlines():
        line=raw.rstrip()
        out.append(line)
    return "\n".join(out).rstrip()+"\n"

def init_project(target: str | Path, force: bool=False) -> Path:
    root=Path(target)
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Directory is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)
    (root/"examples").mkdir(exist_ok=True)
    (root/"tests").mkdir(exist_ok=True)
    (root/"app.ppl").write_text(APP_PPL, encoding='utf-8')
    (root/"script.ppl").write_text(SCRIPT_PPL, encoding='utf-8')
    (root/"ppl.providers.json.example").write_text(PROVIDERS_EXAMPLE, encoding='utf-8')
    (root/"ppl.tools.json.example").write_text(TOOLS_EXAMPLE, encoding='utf-8')
    (root/"README.md").write_text(
        '# PPL App\n\nGenerated by `ppl init`.\n\n'
        '- `script.ppl` — deterministic daily script (no API key)\n'
        '- `app.ppl` — AI workflow example\n\n'
        'Configure provider: `ppl provider show`\n',
        encoding='utf-8',
    )
    return root

def diagnostics_from_exception(exc: Exception) -> str:
    return f"ERROR: {exc.__class__.__name__}: {exc}"

def repl_lines(lines: Iterable[str]) -> list[str]:
    results=[]
    for line in lines:
        s=line.strip()
        if not s: continue
        if s in {':help',':quit',':exit'}: results.append(s)
        else: results.append(f'accepted: {s}')
    return results
